### PR TITLE
Delete your own cheeps

### PR DESCRIPTION
**Pull request by Powsdaws**
It is now possible to delete your own cheeps

### CODE REVIEW

**Review by mortfb — APPROVED** [review]
Looks good

**Review by KassandraW — COMMENTED** [review]
Nice! And nice you added tests B)

One thing - when having two tabs open, and deleting the same cheep on both, it throws an exception - is this what we want?

**Comment by KassandraW** [comment]
yippeee, no more exception. Although now it has branch conflicts somehow??

**Review by VernesNemo — APPROVED** [review]
Looks good, im glad you use the cheepid

**Pull request merged**
