### PR TITLE
constrain-cheeps

### PR DESCRIPTION
**Pull request by KassandraW**
Added constraints on cheep length at view model, endpoint and datamodel. Only added a test for Data model constraint though :(

Users cannot input nothing in the "Send Cheep" field

Also added a method in CheepRepository to get all cheeps from an author and a unit test to it.

### CODE REVIEW

**Review by Powsdaws — COMMENTED** [review]
Looks good. I think we should keep the [StringLength(160)] constraint in Cheep.cs to make sure the database cannot have a cheepmessage longer than 160 (if it works)

**Review by VernesNemo — CHANGES_REQUESTED** [review]
Looks grea,t but the stringlength requirement should still be present in Cheep.cs

**Review by VernesNemo — APPROVED** [review]
Looks great!

**Review by Powsdaws — COMMENTED** [review]
Very nice

**Pull request merged**
